services:
  redis:
    image: redis:7-alpine
    container_name: ppt_studio_redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ppt_studio_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ppt_studio_worker
    command: celery -A worker.celery_app.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    depends_on:
      - redis