FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy everything
COPY . .

# Copy entrypoint explicitly
COPY worker_entrypoint.sh /app/worker_entrypoint.sh
RUN chmod +x /app/worker_entrypoint.sh

EXPOSE 8080

CMD ["./worker_entrypoint.sh"]
