# version: '3.8'

# services:
#   # The Redis message broker for Celery
#   redis:
#     image: redis:7-alpine
#     container_name: ppt_studio_redis
#     ports: # Add this section
#       - "6379:6379" # This makes the container's port 6379 available on your Mac's port 6379

#   # The FastAPI web server
#   api:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: ppt_studio_api
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     env_file:
#       - ./.env
#     depends_on:
#       - redis

#   # The Celery worker process
#   worker:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: ppt_studio_worker
#     command: celery -A worker.celery_app.celery worker --loglevel=info
#     volumes:
#       - ./backend:/app
#     env_file:
#       - ./.env
#     depends_on:
#       - redis


# Remove the version: '3.8' line if it's still there
services:
  redis:
    image: redis:7-alpine
    container_name: ppt_studio_redis
    platform: linux/amd64  # <-- Add this line
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ppt_studio_api
    platform: linux/amd64  # <-- Add this line
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ppt_studio_worker
    platform: linux/amd64  # <-- Add this line
    command: celery -A worker.celery_app.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    depends_on:
      - redis